
# This file is used to configure Supabase CLI.

[project]
name = "fitbot"
project_id = "qekzpqtuunzhvrwpqlsy"

[api]
port = 54321
host = "localhost"
schemes = ["http", "https"]
public_url = "https://qekzpqtuunzhvrwpqlsy.supabase.co"

[db]
port = 5432
shadow_port = 5433
major_version = 15

[studio]
port = 54323
browser_command = ""

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://example.com"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
