
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qekzpqtuunzhvrwpqlsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFla3pwcXR1dW56aHZyd3BxbHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTc0NTgsImV4cCI6MjA2MDM3MzQ1OH0.nK9l4pjHZuP-ZrIDzjb9skYc90hq24_2CSHp8hhOeBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    global: {
      fetch: fetch
    }
  }
);
